spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

handlebars:
  suffix: .html
  enabled: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-length: 3600000

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://192.168.4.149:3306/subway
      username: root
      password: masterpw
      driver-class-name: org.mariadb.jdbc.Driver

